from PySide6.QtCore import QObject, Signal

class LanguageSignal(QObject):
    language_changed = Signal(str)

language_signal = LanguageSignal()

LANGUAGES = {
    'TR': {
        'app_title': 'Media Manager Pro',
        'select_folder': 'Lütfen sol taraftan bir klasör seçin veya sürükleyin...',
        'total': 'TOPLAM',
        'images': 'RESİM',
        'videos': 'VİDEO',
        'size': 'BOYUT',
        'filter': '🔍 Filtrele',
        'type': 'Tür:',
        'size_label': 'Boyut:',
        'all': 'Tümü',
        'pictures': 'Resimler',
        'video_label': 'Videolar',
        'other': 'Diğer',
        'small': 'Küçük (<1MB)',
        'medium': 'Orta (1-10MB)',
        'large': 'Büyük (>10MB)',
        'organize': 'DÜZENLE',
        'organize_desc': 'Karışık dosyaları tarihe göre klasörler.',
        'mode': 'Mod:',
        'by_day': 'Güne Göre',
        'by_month': 'Aya Göre',
        'by_year': 'Yıla Göre',
        'theme': 'Tema',
        'turkish': 'Türkçe',
        'english': 'English',
        'unexpected_error_main': 'Beklenmedik Hata',
        'error_main': 'Bir beklenmedik hata oluştu.',
        'report_error_main': 'Lütfen bu hatayı geliştiriciye bildirin.',
        'processed': 'işlendi',
        'themes': 'Temalar',
        'dark_theme_name': 'Koyu Tema',
        'light_theme_name': 'Açık Tema',
        'confirm_overwrite': 'Dosya zaten var. Üstüne yazılsın mı?',
        'confirm_skip': 'Dosya zaten var. Atlanacak mı?',
        'confirm_copy': 'Dosya zaten var. Kopyası oluşturulacak mı?',
        'general_settings': 'Genel Ayarlar',
        'window_geometry': 'Pencere Geometrisi',
        'last_used_folder': 'Son Kullanılan Klasör',
        'conflict': 'Çakışma:',
        'copy': 'Kopyasını Oluştur',
        'overwrite': 'Üstüne Yaz',
        'skip': 'Atla',
        'start_organize': '🚀 Düzenlemeyi Başlat',
        'clean': 'TEMİZLE',
        'clean_desc': 'Birebir aynı dosyaları bulur ve ayırır.',
        'clean_duplicates': '🧹 Kopyaları Temizle',
        'convert': 'DÖNÜŞTÜR',
        'convert_desc': 'Resim formatlarını değiştir.',
        'target': 'Hedef:',
        'convert_btn': '🔄 Dönüştür',
        'privacy': 'GİZLİLİK',
        'privacy_desc': 'Meta verileri (GPS, Kamera) temizler.',
        'privacy_btn': '🛡️ Temizle',
        'repair': 'ONAR',
        'repair_desc': 'Eski fotoğrafları onarır.',
        'repair_btn': '🔧 Onar',
        'file': 'Dosya',
        'open_folder': 'Klasör Aç...',
        'recent': 'Son Klasörler',
        'exit': 'Çıkış',
        'tools': 'Araçlar',
        'plugins': 'Eklentiler',
        'apply': 'Uygula',
        'plugin_reloaded': '🔌 Eklentiler yeniden yüklendi.',
        'plugin_disabled': 'Bu eklenti devre dışı. Önce etkinleştirin.',
        'batch_rename': 'Toplu Yeniden Adlandır',
        'plugin_manager': 'Eklenti Yöneticisi',
        'view': 'Görünüm',
        'themes': 'Temalar',
        'dark_theme': 'Koyu Tema',
        'light_theme': 'Açık Tema',
        'language': 'Dil',
        'select_folder_dialog': 'Klasör Seç',
        'warning': 'Uyarı',
        'select_first': 'Önce bir klasör seçmelisiniz!',
        'error': 'Hata',
        'invalid_pattern': 'Geçersiz desen!',
        'batch_completed': '✅ Toplu adlandırma tamamlandı. Desen: {}',
        'rename_error': '❌ Adlandırma hatası: {}',
        'filters_applied': '🔍 Filtreler: Tür={}, Boyut={}',
        'busy': 'Meşgul',
        'operation_progress': 'İşlem devam ediyor.',
        'save_location': 'Kaydedilecek Yeri Seç',
        'completed': 'Tamamlandı',
        'success': 'İşlem başarıyla bitti!',
        'folder_loaded': 'Klasör yüklendi: {}',
        'selected': '📂 Seçili: {}',
        'analysis_updated': '📊 Analiz güncellendi.',
        'unexpected_error': 'Beklenmedik Hata Oluştu',
        'error_occurred': 'Uygulama çalışırken beklenmedik bir hata meydana geldi.',
        'report_error': 'Lütfen bu hatayı geliştiriciye bildirin.',
        'restart_required': 'Dil değişikliğini uygulamak için lütfen uygulamayı yeniden başlatınız.',
        'info': 'Bilgi',
        'drag_files': '📂 Dosyaları Buraya Sürükleyin',
        'pattern': 'Desen:',
        'original_name': 'Orijinal İsim',
        'date_sequence': 'Tarih_Sıra (örn: 20240101_001)',
        'sequence_name': 'Sıra_İsim (örn: 001_resim)',
        'name_date': 'İsim_Tarih (örn: resim_20240101)',
        'custom_pattern': 'Özel Desen',
        'custom_pattern_label': 'Özel Desen (örn: {name}_{date}_{counter}):',
        'preview': 'Önizleme:',
        'batch_rename_title': 'Toplu Yeniden Adlandırma',
        'detected_plugins': '📂 Algılanan Eklentiler:',
        'description_label': 'Açıklama:',
        'no_description': 'Açıklama yok.',
        'run_plugin': '▶️ Seçili Eklentiyi Çalıştır',
        'refresh': '🔄 Yenile',
        'plugin_manager_title': 'Eklenti Yöneticisi',
        'select_plugin': 'Lütfen bir eklenti seçin.',
        'plugin_error': 'Plugin hatası:',
        'start_analysis': '🚀 Analiz Başladı',
        'start_organizing': '🚀 Düzenleme Başladı...',
        'process_stopped': '🛑 İşlem kullanıcı tarafından durduruldu.',
        'moved': '✅ Taşındı: {}',
        'skipped': '⏩ Atlandı: {}',
        'access_denied': '❌ Erişim Reddedildi: {}',
        'disk_error': '❌ Disk/Dosya Hatası: {} ({})',
        'unexpected_error_file': '❌ Beklenmedik Hata: {} ({})',
        'scan_start': '🔍 Kopya taraması başladı...',
        'duplicate_found': '⚠️ Kopya Bulundu: {}',
        'read_error': '❌ Okuma İzni Yok: {}',
        'duplicate_folder': 'Mükerrer_Dosyalar',
        'moved_to_duplicates': '🗑️ Taşındı: {}',
        'move_error': '❌ Taşıma Hatası: {} ({})',
        'error_file': '❌ Hata: {} ({})',
        'converting': '🔄 Dönüştürülüyor -> {}',
        'converted': '✅ Çevrildi: {}',
        'corrupt_image': '❌ Bozuk/Tanımsız Resim: {}',
        'save_error': '❌ Kaydetme Hatası: {} ({})',
        'unknown_error': '❌ Bilinmeyen Hata ({}): {}',
        'cleaning_metadata': '🛡️ Meta veriler temizleniyor...',
        'cleaned_inplace': '🔒 Yerinde Temizlendi: {}',
        'saved_to_folder': '🔒 Klasöre Kaydedildi: {}',
        'repair_start': '🔧 Onarım başladı (Telea Algoritması)...',
        'repaired': '✨ Onarıldı: {}',
        'missing_repair_deps': '❌ Onarım özelliği için OpenCV + NumPy + scikit-image gerekli.',
        'opencv_error': '❌ OpenCV Hatası: {}',
        'conflict_copy_exists': 'Dosya zaten var. Kopyasını oluşturulmuştur.',
        'conflict_skip': 'Dosya zaten var. Atlanmıştır.',
    },
    'EN': {
        'app_title': 'Media Manager Pro',
        'select_folder': 'Please select or drag a folder from the left...',
        'total': 'TOTAL',
        'images': 'IMAGES',
        'videos': 'VIDEOS',
        'size': 'SIZE',
        'filter': '🔍 Filter',
        'type': 'Type:',
        'size_label': 'Size:',
        'all': 'All',
        'pictures': 'Pictures',
        'video_label': 'Videos',
        'other': 'Other',
        'small': 'Small (<1MB)',
        'medium': 'Medium (1-10MB)',
        'large': 'Large (>10MB)',
        'organize': 'ORGANIZE',
        'organize_desc': 'Organize mixed files into date-based folders.',
        'mode': 'Mode:',
        'by_day': 'By Day',
        'by_month': 'By Month',
        'by_year': 'By Year',
        'theme': 'Theme',
        'turkish': 'Türkçe',
        'english': 'English',
        'unexpected_error_main': 'Unexpected Error',
        'error_main': 'An unexpected error occurred.',
        'report_error_main': 'Please report this error to the developer.',
        'processed': 'processed',
        'themes': 'Themes',
        'dark_theme_name': 'Dark Theme',
        'light_theme_name': 'Light Theme',
        'confirm_overwrite': 'File already exists. Overwrite?',
        'confirm_skip': 'File already exists. Skip?',
        'confirm_copy': 'File already exists. Create copy?',
        'general_settings': 'General Settings',
        'window_geometry': 'Window Geometry',
        'last_used_folder': 'Last Used Folder',
        'conflict': 'Conflict:',
        'copy': 'Create Copy',
        'overwrite': 'Overwrite',
        'skip': 'Skip',
        'start_organize': '🚀 Start Organizing',
        'clean': 'CLEAN',
        'clean_desc': 'Find and separate identical files.',
        'clean_duplicates': '🧹 Clean Duplicates',
        'convert': 'CONVERT',
        'convert_desc': 'Convert image formats.',
        'target': 'Target:',
        'convert_btn': '🔄 Convert',
        'privacy': 'PRIVACY',
        'privacy_desc': 'Remove metadata (GPS, Camera info).',
        'privacy_btn': '🛡️ Clean',
        'repair': 'REPAIR',
        'repair_desc': 'Repair old photos.',
        'repair_btn': '🔧 Repair',
        'file': 'File',
        'open_folder': 'Open Folder...',
        'recent': 'Recent Folders',
        'exit': 'Exit',
        'tools': 'Tools',
        'plugins': 'Plugins',
        'apply': 'Apply',
        'plugin_reloaded': '🔌 Plugins reloaded.',
        'plugin_disabled': 'This plugin is disabled. Enable it first.',
        'batch_rename': 'Batch Rename',
        'plugin_manager': 'Plugin Manager',
        'view': 'View',
        'themes': 'Themes',
        'dark_theme': 'Dark Theme',
        'light_theme': 'Light Theme',
        'language': 'Language',
        'select_folder_dialog': 'Select Folder',
        'warning': 'Warning',
        'select_first': 'Please select a folder first!',
        'error': 'Error',
        'invalid_pattern': 'Invalid pattern!',
        'batch_completed': '✅ Batch rename completed. Pattern: {}',
        'rename_error': '❌ Rename error: {}',
        'filters_applied': '🔍 Filters: Type={}, Size={}',
        'busy': 'Busy',
        'operation_progress': 'Operation in progress.',
        'save_location': 'Select Save Location',
        'completed': 'Completed',
        'success': 'Operation finished successfully!',
        'folder_loaded': 'Folder loaded: {}',
        'selected': '📂 Selected: {}',
        'analysis_updated': '📊 Analysis updated.',
        'unexpected_error': 'Unexpected Error Occurred',
        'error_occurred': 'An unexpected error occurred while running the application.',
        'report_error': 'Please report this error to the developer.',
        'restart_required': 'Please restart the application to apply language changes.',
        'info': 'Information',
        'drag_files': '📂 Drag Files Here',
        'pattern': 'Pattern:',
        'original_name': 'Original Name',
        'date_sequence': 'Date_Sequence (e.g: 20240101_001)',
        'sequence_name': 'Sequence_Name (e.g: 001_photo)',
        'name_date': 'Name_Date (e.g: photo_20240101)',
        'custom_pattern': 'Custom Pattern',
        'custom_pattern_label': 'Custom Pattern (e.g: {name}_{date}_{counter}):',
        'preview': 'Preview:',
        'batch_rename_title': 'Batch Rename',
        'detected_plugins': '📂 Detected Plugins:',
        'description_label': 'Description:',
        'no_description': 'No description.',
        'run_plugin': '▶️ Run Selected Plugin',
        'refresh': '🔄 Refresh',
        'plugin_manager_title': 'Plugin Manager',
        'select_plugin': 'Please select a plugin.',
        'plugin_error': 'Plugin error:',
        'start_analysis': '🚀 Analysis Started',
        'start_organizing': '🚀 Organizing Started...',
        'process_stopped': '🛑 Process stopped by user.',
        'moved': '✅ Moved: {}',
        'skipped': '⏩ Skipped: {}',
        'access_denied': '❌ Access Denied: {}',
        'disk_error': '❌ Disk/File Error: {} ({})',
        'unexpected_error_file': '❌ Unexpected Error: {} ({})',
        'scan_start': '🔍 Duplicate scan started...',
        'duplicate_found': '⚠️ Duplicate Found: {}',
        'read_error': '❌ Read Permission Denied: {}',
        'duplicate_folder': 'Duplicate_Files',
        'moved_to_duplicates': '🗑️ Moved: {}',
        'move_error': '❌ Move Error: {} ({})',
        'error_file': '❌ Error: {} ({})',
        'converting': '🔄 Converting -> {}',
        'converted': '✅ Converted: {}',
        'corrupt_image': '❌ Corrupt/Unknown Image: {}',
        'save_error': '❌ Save Error: {} ({})',
        'unknown_error': '❌ Unknown Error ({}): {}',
        'cleaning_metadata': '🛡️ Cleaning metadata...',
        'cleaned_inplace': '🔒 Cleaned in place: {}',
        'saved_to_folder': '🔒 Saved to folder: {}',
        'repair_start': '🔧 Repair started (Telea Algorithm)...',
        'repaired': '✨ Repaired: {}',
        'missing_repair_deps': '❌ Repair requires OpenCV + NumPy + scikit-image.',
        'opencv_error': '❌ OpenCV Error: {}',
        'conflict_copy_exists': 'File already exists. Copy created.',
        'conflict_skip': 'File already exists. Skipped.',
    }
}
